#! /bin/sh
set -e

if [ "$1" = "configure" ] && \
   [ -x /usr/lib/emacsen-common/emacs-package-install ]; then
    /usr/lib/emacsen-common/emacs-package-install erc
fi

if [ "$1" = "configure" ]; then
    install-info --quiet --section "Emacs" "emacs" /usr/share/info/erc.info
fi
